sudo: required
services:
  - neo4j
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - sudo apt-get install curl libc6 libcurl3 zlib1g
  - curl -H "Content-Type:application/json" -X POST -d '{"password":"enter"}' -u neo4j:neo4j http://0.0.0.0:7474/user/neo4j/password

before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
