sudo: required
services:
  - neo4j
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - sudo apt-get update && apt-get install httpie
  - http -a neo4j:neo4j POST http://localhost:7474/user/neo4j/password password=enter

before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
