sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  docker run \
      --publish=7474:7474 --publish=7687:7687 \
      --volume=$HOME/neo4j/data:/data \
      --volume=$HOME/neo4j/logs:/logs \
      neo4j:3.0
before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
