sudo: required
services:
  - neo4j
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - cd /tmp
  - wget https://goo.gl/DhZejK -O httpie_0.8.0-1_arm64.deb
  - sudo dpkg -i --force-depends httpie_0.8.0-1_arm64.deb
  - sudo apt-get -f install
  - http -a neo4j:neo4j POST http://localhost:7474/user/neo4j/password password=enter

before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
